package ejercicios;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author emiliomurillo
 */
public class PanelRecta extends javax.swing.JPanel {
    JLabel lbl_distancia, lbl_resultado;

    public PanelRecta() {
        initComponents();
        lbl_distancia = new JLabel("La distancia entre los dos puntos es de: "); 
        Recta resul = ResultadoFinal.resultado;
        lbl_resultado = new JLabel((String.valueOf(resul.distancia())));
        //lbl_resultado.setText("13");
        
        this.add(lbl_distancia);
        this.add(lbl_resultado);
        
        lbl_distancia.setBounds(200, 50, 465, 50);
        lbl_distancia.setFont(new Font("Algerian", Font.BOLD, 20));
        lbl_resultado.setBounds(300, 100, 210, 50);
        lbl_resultado.setFont(new Font("Algerian", Font.BOLD, 15));
        
        this.setBackground(new Color(0, 255, 255));
        this.setSize(680, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
